#define CLASH_XP_CLUTCH 25
#define CLASH_XP_PAYBACK 50
#define CLASH_CLUTCH_RANGE 7
#define CLASH_PAYBACK_WINDOW (30 SECONDS)
#define CLASH_MEDIC_SHOUT_MARK (15 SECONDS)

#define CLASH_XP_SOURCE_CLUTCH "Clutch revive"
#define CLASH_XP_SOURCE_PAYBACK "Payback"
